apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: echoserver
          image: "jmalloc/echo-server:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "{{ .Values.deployment.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
            
